/* AUTOGENERATED FILE - DO NOT EDIT */
export const projectId = 'blibawahlbufacgjzqok';
export const publicAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsaWJhd2FobGJ1ZmFjZ2p6cW9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NjI0MDAsImV4cCI6MjA2MTMzODQwMH0.8B_cSRrXV5m8pWSj6OEu_GJ3-vb4kqiKD9Rh2zXN9Vs';
